name: Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (Tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ip-monitor
          tags: |
            type=raw,value=latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./ipchecker       # Looks for the build context here
          file: ./ipchecker/Dockerfile # Points to the Dockerfile path
          push: true
          tags: ${{ steps.meta.outputs.tags }}
